[workspace]
members = [
    "intelhex",
    "hexviewer",
]
resolver = "3"

[workspace.package]
name = "hexalyzer"
version = "0.1.0"
edition = "2024"
description = "Intel HEX parser & hex viewer GUI"
license = "MIT"